//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hazzat.HazzatService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeasonInfo", Namespace="http://hazzat.com/")]
    public partial class SeasonInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ItemIdField;
        
        private string NameField;
        
        private int ServiceHymnsCountField;
        
        private string VerseField;
        
        private int Season_OrderField;
        
        private int Reason_IDField;
        
        private string Reason_NameField;
        
        private bool Date_SpecificField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((this.ItemIdField.Equals(value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ServiceHymnsCount {
            get {
                return this.ServiceHymnsCountField;
            }
            set {
                if ((this.ServiceHymnsCountField.Equals(value) != true)) {
                    this.ServiceHymnsCountField = value;
                    this.RaisePropertyChanged("ServiceHymnsCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Verse {
            get {
                return this.VerseField;
            }
            set {
                if ((object.ReferenceEquals(this.VerseField, value) != true)) {
                    this.VerseField = value;
                    this.RaisePropertyChanged("Verse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Season_Order {
            get {
                return this.Season_OrderField;
            }
            set {
                if ((this.Season_OrderField.Equals(value) != true)) {
                    this.Season_OrderField = value;
                    this.RaisePropertyChanged("Season_Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Reason_ID {
            get {
                return this.Reason_IDField;
            }
            set {
                if ((this.Reason_IDField.Equals(value) != true)) {
                    this.Reason_IDField = value;
                    this.RaisePropertyChanged("Reason_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Reason_Name {
            get {
                return this.Reason_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Reason_NameField, value) != true)) {
                    this.Reason_NameField = value;
                    this.RaisePropertyChanged("Reason_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool Date_Specific {
            get {
                return this.Date_SpecificField;
            }
            set {
                if ((this.Date_SpecificField.Equals(value) != true)) {
                    this.Date_SpecificField = value;
                    this.RaisePropertyChanged("Date_Specific");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructureInfo", Namespace="http://hazzat.com/")]
    public partial class StructureInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ItemIdField;
        
        private string NameField;
        
        private int Season_IDField;
        
        private string Season_NameField;
        
        private string Season_VerseField;
        
        private int Reason_IDField;
        
        private int Service_OrderField;
        
        private int Service_IDField;
        
        private string Service_NameField;
        
        private bool Has_TextField;
        
        private bool Has_HazzatField;
        
        private bool Has_VerticalHazzatField;
        
        private bool Has_MusicField;
        
        private bool Has_AudioField;
        
        private bool Has_VideoField;
        
        private bool Has_InformationField;
        
        private int Text_CountField;
        
        private int Hazzat_CountField;
        
        private int VerticalHazzat_CountField;
        
        private int Music_CountField;
        
        private int Audio_CountField;
        
        private int Video_CountField;
        
        private int Information_CountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((this.ItemIdField.Equals(value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Season_ID {
            get {
                return this.Season_IDField;
            }
            set {
                if ((this.Season_IDField.Equals(value) != true)) {
                    this.Season_IDField = value;
                    this.RaisePropertyChanged("Season_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Season_Name {
            get {
                return this.Season_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Season_NameField, value) != true)) {
                    this.Season_NameField = value;
                    this.RaisePropertyChanged("Season_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Season_Verse {
            get {
                return this.Season_VerseField;
            }
            set {
                if ((object.ReferenceEquals(this.Season_VerseField, value) != true)) {
                    this.Season_VerseField = value;
                    this.RaisePropertyChanged("Season_Verse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Reason_ID {
            get {
                return this.Reason_IDField;
            }
            set {
                if ((this.Reason_IDField.Equals(value) != true)) {
                    this.Reason_IDField = value;
                    this.RaisePropertyChanged("Reason_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Service_Order {
            get {
                return this.Service_OrderField;
            }
            set {
                if ((this.Service_OrderField.Equals(value) != true)) {
                    this.Service_OrderField = value;
                    this.RaisePropertyChanged("Service_Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Service_ID {
            get {
                return this.Service_IDField;
            }
            set {
                if ((this.Service_IDField.Equals(value) != true)) {
                    this.Service_IDField = value;
                    this.RaisePropertyChanged("Service_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Service_Name {
            get {
                return this.Service_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Service_NameField, value) != true)) {
                    this.Service_NameField = value;
                    this.RaisePropertyChanged("Service_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool Has_Text {
            get {
                return this.Has_TextField;
            }
            set {
                if ((this.Has_TextField.Equals(value) != true)) {
                    this.Has_TextField = value;
                    this.RaisePropertyChanged("Has_Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool Has_Hazzat {
            get {
                return this.Has_HazzatField;
            }
            set {
                if ((this.Has_HazzatField.Equals(value) != true)) {
                    this.Has_HazzatField = value;
                    this.RaisePropertyChanged("Has_Hazzat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public bool Has_VerticalHazzat {
            get {
                return this.Has_VerticalHazzatField;
            }
            set {
                if ((this.Has_VerticalHazzatField.Equals(value) != true)) {
                    this.Has_VerticalHazzatField = value;
                    this.RaisePropertyChanged("Has_VerticalHazzat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool Has_Music {
            get {
                return this.Has_MusicField;
            }
            set {
                if ((this.Has_MusicField.Equals(value) != true)) {
                    this.Has_MusicField = value;
                    this.RaisePropertyChanged("Has_Music");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool Has_Audio {
            get {
                return this.Has_AudioField;
            }
            set {
                if ((this.Has_AudioField.Equals(value) != true)) {
                    this.Has_AudioField = value;
                    this.RaisePropertyChanged("Has_Audio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public bool Has_Video {
            get {
                return this.Has_VideoField;
            }
            set {
                if ((this.Has_VideoField.Equals(value) != true)) {
                    this.Has_VideoField = value;
                    this.RaisePropertyChanged("Has_Video");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public bool Has_Information {
            get {
                return this.Has_InformationField;
            }
            set {
                if ((this.Has_InformationField.Equals(value) != true)) {
                    this.Has_InformationField = value;
                    this.RaisePropertyChanged("Has_Information");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public int Text_Count {
            get {
                return this.Text_CountField;
            }
            set {
                if ((this.Text_CountField.Equals(value) != true)) {
                    this.Text_CountField = value;
                    this.RaisePropertyChanged("Text_Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public int Hazzat_Count {
            get {
                return this.Hazzat_CountField;
            }
            set {
                if ((this.Hazzat_CountField.Equals(value) != true)) {
                    this.Hazzat_CountField = value;
                    this.RaisePropertyChanged("Hazzat_Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public int VerticalHazzat_Count {
            get {
                return this.VerticalHazzat_CountField;
            }
            set {
                if ((this.VerticalHazzat_CountField.Equals(value) != true)) {
                    this.VerticalHazzat_CountField = value;
                    this.RaisePropertyChanged("VerticalHazzat_Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public int Music_Count {
            get {
                return this.Music_CountField;
            }
            set {
                if ((this.Music_CountField.Equals(value) != true)) {
                    this.Music_CountField = value;
                    this.RaisePropertyChanged("Music_Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public int Audio_Count {
            get {
                return this.Audio_CountField;
            }
            set {
                if ((this.Audio_CountField.Equals(value) != true)) {
                    this.Audio_CountField = value;
                    this.RaisePropertyChanged("Audio_Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public int Video_Count {
            get {
                return this.Video_CountField;
            }
            set {
                if ((this.Video_CountField.Equals(value) != true)) {
                    this.Video_CountField = value;
                    this.RaisePropertyChanged("Video_Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public int Information_Count {
            get {
                return this.Information_CountField;
            }
            set {
                if ((this.Information_CountField.Equals(value) != true)) {
                    this.Information_CountField = value;
                    this.RaisePropertyChanged("Information_Count");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceHymnInfo", Namespace="http://hazzat.com/")]
    public partial class ServiceHymnInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ItemIdField;
        
        private int Structure_IDField;
        
        private int Season_IDField;
        
        private string Season_NameField;
        
        private string Season_VerseField;
        
        private int Reason_IDField;
        
        private string Structure_NameField;
        
        private string Service_NameField;
        
        private int Hymn_OrderField;
        
        private string TitleField;
        
        private string ServiceHymn_LongTitleField;
        
        private bool Has_TextField;
        
        private bool Has_HazzatField;
        
        private bool Has_VerticalHazzatField;
        
        private bool Has_MusicField;
        
        private bool Has_AudioField;
        
        private bool Has_VideoField;
        
        private bool Has_InformationField;
        
        private int Text_CountField;
        
        private int Hazzat_CountField;
        
        private int VerticalHazzat_CountField;
        
        private int Music_CountField;
        
        private int Audio_CountField;
        
        private int Video_CountField;
        
        private int Information_CountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((this.ItemIdField.Equals(value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Structure_ID {
            get {
                return this.Structure_IDField;
            }
            set {
                if ((this.Structure_IDField.Equals(value) != true)) {
                    this.Structure_IDField = value;
                    this.RaisePropertyChanged("Structure_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Season_ID {
            get {
                return this.Season_IDField;
            }
            set {
                if ((this.Season_IDField.Equals(value) != true)) {
                    this.Season_IDField = value;
                    this.RaisePropertyChanged("Season_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Season_Name {
            get {
                return this.Season_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Season_NameField, value) != true)) {
                    this.Season_NameField = value;
                    this.RaisePropertyChanged("Season_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Season_Verse {
            get {
                return this.Season_VerseField;
            }
            set {
                if ((object.ReferenceEquals(this.Season_VerseField, value) != true)) {
                    this.Season_VerseField = value;
                    this.RaisePropertyChanged("Season_Verse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Reason_ID {
            get {
                return this.Reason_IDField;
            }
            set {
                if ((this.Reason_IDField.Equals(value) != true)) {
                    this.Reason_IDField = value;
                    this.RaisePropertyChanged("Reason_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Structure_Name {
            get {
                return this.Structure_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Structure_NameField, value) != true)) {
                    this.Structure_NameField = value;
                    this.RaisePropertyChanged("Structure_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Service_Name {
            get {
                return this.Service_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Service_NameField, value) != true)) {
                    this.Service_NameField = value;
                    this.RaisePropertyChanged("Service_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Hymn_Order {
            get {
                return this.Hymn_OrderField;
            }
            set {
                if ((this.Hymn_OrderField.Equals(value) != true)) {
                    this.Hymn_OrderField = value;
                    this.RaisePropertyChanged("Hymn_Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ServiceHymn_LongTitle {
            get {
                return this.ServiceHymn_LongTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceHymn_LongTitleField, value) != true)) {
                    this.ServiceHymn_LongTitleField = value;
                    this.RaisePropertyChanged("ServiceHymn_LongTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public bool Has_Text {
            get {
                return this.Has_TextField;
            }
            set {
                if ((this.Has_TextField.Equals(value) != true)) {
                    this.Has_TextField = value;
                    this.RaisePropertyChanged("Has_Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool Has_Hazzat {
            get {
                return this.Has_HazzatField;
            }
            set {
                if ((this.Has_HazzatField.Equals(value) != true)) {
                    this.Has_HazzatField = value;
                    this.RaisePropertyChanged("Has_Hazzat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool Has_VerticalHazzat {
            get {
                return this.Has_VerticalHazzatField;
            }
            set {
                if ((this.Has_VerticalHazzatField.Equals(value) != true)) {
                    this.Has_VerticalHazzatField = value;
                    this.RaisePropertyChanged("Has_VerticalHazzat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public bool Has_Music {
            get {
                return this.Has_MusicField;
            }
            set {
                if ((this.Has_MusicField.Equals(value) != true)) {
                    this.Has_MusicField = value;
                    this.RaisePropertyChanged("Has_Music");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public bool Has_Audio {
            get {
                return this.Has_AudioField;
            }
            set {
                if ((this.Has_AudioField.Equals(value) != true)) {
                    this.Has_AudioField = value;
                    this.RaisePropertyChanged("Has_Audio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public bool Has_Video {
            get {
                return this.Has_VideoField;
            }
            set {
                if ((this.Has_VideoField.Equals(value) != true)) {
                    this.Has_VideoField = value;
                    this.RaisePropertyChanged("Has_Video");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public bool Has_Information {
            get {
                return this.Has_InformationField;
            }
            set {
                if ((this.Has_InformationField.Equals(value) != true)) {
                    this.Has_InformationField = value;
                    this.RaisePropertyChanged("Has_Information");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public int Text_Count {
            get {
                return this.Text_CountField;
            }
            set {
                if ((this.Text_CountField.Equals(value) != true)) {
                    this.Text_CountField = value;
                    this.RaisePropertyChanged("Text_Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public int Hazzat_Count {
            get {
                return this.Hazzat_CountField;
            }
            set {
                if ((this.Hazzat_CountField.Equals(value) != true)) {
                    this.Hazzat_CountField = value;
                    this.RaisePropertyChanged("Hazzat_Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public int VerticalHazzat_Count {
            get {
                return this.VerticalHazzat_CountField;
            }
            set {
                if ((this.VerticalHazzat_CountField.Equals(value) != true)) {
                    this.VerticalHazzat_CountField = value;
                    this.RaisePropertyChanged("VerticalHazzat_Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public int Music_Count {
            get {
                return this.Music_CountField;
            }
            set {
                if ((this.Music_CountField.Equals(value) != true)) {
                    this.Music_CountField = value;
                    this.RaisePropertyChanged("Music_Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public int Audio_Count {
            get {
                return this.Audio_CountField;
            }
            set {
                if ((this.Audio_CountField.Equals(value) != true)) {
                    this.Audio_CountField = value;
                    this.RaisePropertyChanged("Audio_Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public int Video_Count {
            get {
                return this.Video_CountField;
            }
            set {
                if ((this.Video_CountField.Equals(value) != true)) {
                    this.Video_CountField = value;
                    this.RaisePropertyChanged("Video_Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public int Information_Count {
            get {
                return this.Information_CountField;
            }
            set {
                if ((this.Information_CountField.Equals(value) != true)) {
                    this.Information_CountField = value;
                    this.RaisePropertyChanged("Information_Count");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceHymnsContentInfo", Namespace="http://hazzat.com/")]
    public partial class ServiceHymnsContentInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ItemIdField;
        
        private string TitleField;
        
        private string Structure_NameField;
        
        private int ServiceHymn_IDField;
        
        private string ServiceHymn_NameField;
        
        private int Content_IDField;
        
        private int Format_IDField;
        
        private string Format_NameField;
        
        private int Type_IDField;
        
        private string Type_NameField;
        
        private int Tune_IDField;
        
        private string Tune_NameField;
        
        private string InfoField;
        
        private string Content_EnglishField;
        
        private string Content_CopticField;
        
        private string Content_ArabicField;
        
        private System.DateTime Updated_TimeStampField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((this.ItemIdField.Equals(value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Structure_Name {
            get {
                return this.Structure_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Structure_NameField, value) != true)) {
                    this.Structure_NameField = value;
                    this.RaisePropertyChanged("Structure_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int ServiceHymn_ID {
            get {
                return this.ServiceHymn_IDField;
            }
            set {
                if ((this.ServiceHymn_IDField.Equals(value) != true)) {
                    this.ServiceHymn_IDField = value;
                    this.RaisePropertyChanged("ServiceHymn_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ServiceHymn_Name {
            get {
                return this.ServiceHymn_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceHymn_NameField, value) != true)) {
                    this.ServiceHymn_NameField = value;
                    this.RaisePropertyChanged("ServiceHymn_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Content_ID {
            get {
                return this.Content_IDField;
            }
            set {
                if ((this.Content_IDField.Equals(value) != true)) {
                    this.Content_IDField = value;
                    this.RaisePropertyChanged("Content_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Format_ID {
            get {
                return this.Format_IDField;
            }
            set {
                if ((this.Format_IDField.Equals(value) != true)) {
                    this.Format_IDField = value;
                    this.RaisePropertyChanged("Format_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Format_Name {
            get {
                return this.Format_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Format_NameField, value) != true)) {
                    this.Format_NameField = value;
                    this.RaisePropertyChanged("Format_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Type_ID {
            get {
                return this.Type_IDField;
            }
            set {
                if ((this.Type_IDField.Equals(value) != true)) {
                    this.Type_IDField = value;
                    this.RaisePropertyChanged("Type_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Type_Name {
            get {
                return this.Type_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Type_NameField, value) != true)) {
                    this.Type_NameField = value;
                    this.RaisePropertyChanged("Type_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int Tune_ID {
            get {
                return this.Tune_IDField;
            }
            set {
                if ((this.Tune_IDField.Equals(value) != true)) {
                    this.Tune_IDField = value;
                    this.RaisePropertyChanged("Tune_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Tune_Name {
            get {
                return this.Tune_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Tune_NameField, value) != true)) {
                    this.Tune_NameField = value;
                    this.RaisePropertyChanged("Tune_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Content_English {
            get {
                return this.Content_EnglishField;
            }
            set {
                if ((object.ReferenceEquals(this.Content_EnglishField, value) != true)) {
                    this.Content_EnglishField = value;
                    this.RaisePropertyChanged("Content_English");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Content_Coptic {
            get {
                return this.Content_CopticField;
            }
            set {
                if ((object.ReferenceEquals(this.Content_CopticField, value) != true)) {
                    this.Content_CopticField = value;
                    this.RaisePropertyChanged("Content_Coptic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Content_Arabic {
            get {
                return this.Content_ArabicField;
            }
            set {
                if ((object.ReferenceEquals(this.Content_ArabicField, value) != true)) {
                    this.Content_ArabicField = value;
                    this.RaisePropertyChanged("Content_Arabic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public System.DateTime Updated_TimeStamp {
            get {
                return this.Updated_TimeStampField;
            }
            set {
                if ((this.Updated_TimeStampField.Equals(value) != true)) {
                    this.Updated_TimeStampField = value;
                    this.RaisePropertyChanged("Updated_TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://hazzat.com/", ConfigurationName="HazzatService.HazzatWebServiceSoap")]
    public interface HazzatWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hazzat.com/GetSeasons", ReplyAction="*")]
        System.IAsyncResult BeginGetSeasons(Hazzat.HazzatService.GetSeasonsRequest request, System.AsyncCallback callback, object asyncState);
        
        Hazzat.HazzatService.GetSeasonsResponse EndGetSeasons(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hazzat.com/GetSeasonServices", ReplyAction="*")]
        System.IAsyncResult BeginGetSeasonServices(Hazzat.HazzatService.GetSeasonServicesRequest request, System.AsyncCallback callback, object asyncState);
        
        Hazzat.HazzatService.GetSeasonServicesResponse EndGetSeasonServices(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hazzat.com/GetSeasonServiceHymns", ReplyAction="*")]
        System.IAsyncResult BeginGetSeasonServiceHymns(Hazzat.HazzatService.GetSeasonServiceHymnsRequest request, System.AsyncCallback callback, object asyncState);
        
        Hazzat.HazzatService.GetSeasonServiceHymnsResponse EndGetSeasonServiceHymns(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hazzat.com/GetSeasonServiceHymnText", ReplyAction="*")]
        System.IAsyncResult BeginGetSeasonServiceHymnText(Hazzat.HazzatService.GetSeasonServiceHymnTextRequest request, System.AsyncCallback callback, object asyncState);
        
        Hazzat.HazzatService.GetSeasonServiceHymnTextResponse EndGetSeasonServiceHymnText(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class GetSeasonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasons", Namespace="http://hazzat.com/", Order=0)]
        public Hazzat.HazzatService.GetSeasonsRequestBody Body;
        
        public GetSeasonsRequest() {
        }
        
        public GetSeasonsRequest(Hazzat.HazzatService.GetSeasonsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
    public partial class GetSeasonsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isDateSpecific;
        
        public GetSeasonsRequestBody() {
        }
        
        public GetSeasonsRequestBody(bool isDateSpecific) {
            this.isDateSpecific = isDateSpecific;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class GetSeasonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasonsResponse", Namespace="http://hazzat.com/", Order=0)]
        public Hazzat.HazzatService.GetSeasonsResponseBody Body;
        
        public GetSeasonsResponse() {
        }
        
        public GetSeasonsResponse(Hazzat.HazzatService.GetSeasonsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
    public partial class GetSeasonsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.SeasonInfo> GetSeasonsResult;
        
        public GetSeasonsResponseBody() {
        }
        
        public GetSeasonsResponseBody(System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.SeasonInfo> GetSeasonsResult) {
            this.GetSeasonsResult = GetSeasonsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class GetSeasonServicesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasonServices", Namespace="http://hazzat.com/", Order=0)]
        public Hazzat.HazzatService.GetSeasonServicesRequestBody Body;
        
        public GetSeasonServicesRequest() {
        }
        
        public GetSeasonServicesRequest(Hazzat.HazzatService.GetSeasonServicesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
    public partial class GetSeasonServicesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int seasonId;
        
        public GetSeasonServicesRequestBody() {
        }
        
        public GetSeasonServicesRequestBody(int seasonId) {
            this.seasonId = seasonId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class GetSeasonServicesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasonServicesResponse", Namespace="http://hazzat.com/", Order=0)]
        public Hazzat.HazzatService.GetSeasonServicesResponseBody Body;
        
        public GetSeasonServicesResponse() {
        }
        
        public GetSeasonServicesResponse(Hazzat.HazzatService.GetSeasonServicesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
    public partial class GetSeasonServicesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.StructureInfo> GetSeasonServicesResult;
        
        public GetSeasonServicesResponseBody() {
        }
        
        public GetSeasonServicesResponseBody(System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.StructureInfo> GetSeasonServicesResult) {
            this.GetSeasonServicesResult = GetSeasonServicesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class GetSeasonServiceHymnsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasonServiceHymns", Namespace="http://hazzat.com/", Order=0)]
        public Hazzat.HazzatService.GetSeasonServiceHymnsRequestBody Body;
        
        public GetSeasonServiceHymnsRequest() {
        }
        
        public GetSeasonServiceHymnsRequest(Hazzat.HazzatService.GetSeasonServiceHymnsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
    public partial class GetSeasonServiceHymnsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int structureId;
        
        public GetSeasonServiceHymnsRequestBody() {
        }
        
        public GetSeasonServiceHymnsRequestBody(int structureId) {
            this.structureId = structureId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class GetSeasonServiceHymnsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasonServiceHymnsResponse", Namespace="http://hazzat.com/", Order=0)]
        public Hazzat.HazzatService.GetSeasonServiceHymnsResponseBody Body;
        
        public GetSeasonServiceHymnsResponse() {
        }
        
        public GetSeasonServiceHymnsResponse(Hazzat.HazzatService.GetSeasonServiceHymnsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
    public partial class GetSeasonServiceHymnsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.ServiceHymnInfo> GetSeasonServiceHymnsResult;
        
        public GetSeasonServiceHymnsResponseBody() {
        }
        
        public GetSeasonServiceHymnsResponseBody(System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.ServiceHymnInfo> GetSeasonServiceHymnsResult) {
            this.GetSeasonServiceHymnsResult = GetSeasonServiceHymnsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class GetSeasonServiceHymnTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasonServiceHymnText", Namespace="http://hazzat.com/", Order=0)]
        public Hazzat.HazzatService.GetSeasonServiceHymnTextRequestBody Body;
        
        public GetSeasonServiceHymnTextRequest() {
        }
        
        public GetSeasonServiceHymnTextRequest(Hazzat.HazzatService.GetSeasonServiceHymnTextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
    public partial class GetSeasonServiceHymnTextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ServiceHymnId;
        
        public GetSeasonServiceHymnTextRequestBody() {
        }
        
        public GetSeasonServiceHymnTextRequestBody(int ServiceHymnId) {
            this.ServiceHymnId = ServiceHymnId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class GetSeasonServiceHymnTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasonServiceHymnTextResponse", Namespace="http://hazzat.com/", Order=0)]
        public Hazzat.HazzatService.GetSeasonServiceHymnTextResponseBody Body;
        
        public GetSeasonServiceHymnTextResponse() {
        }
        
        public GetSeasonServiceHymnTextResponse(Hazzat.HazzatService.GetSeasonServiceHymnTextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
    public partial class GetSeasonServiceHymnTextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.ServiceHymnsContentInfo> GetSeasonServiceHymnTextResult;
        
        public GetSeasonServiceHymnTextResponseBody() {
        }
        
        public GetSeasonServiceHymnTextResponseBody(System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.ServiceHymnsContentInfo> GetSeasonServiceHymnTextResult) {
            this.GetSeasonServiceHymnTextResult = GetSeasonServiceHymnTextResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HazzatWebServiceSoapChannel : Hazzat.HazzatService.HazzatWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSeasonsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSeasonsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.SeasonInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.SeasonInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSeasonServicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSeasonServicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.StructureInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.StructureInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSeasonServiceHymnsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSeasonServiceHymnsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.ServiceHymnInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.ServiceHymnInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSeasonServiceHymnTextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSeasonServiceHymnTextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.ServiceHymnsContentInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.ServiceHymnsContentInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HazzatWebServiceSoapClient : System.ServiceModel.ClientBase<Hazzat.HazzatService.HazzatWebServiceSoap>, Hazzat.HazzatService.HazzatWebServiceSoap {
        
        private BeginOperationDelegate onBeginGetSeasonsDelegate;
        
        private EndOperationDelegate onEndGetSeasonsDelegate;
        
        private System.Threading.SendOrPostCallback onGetSeasonsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSeasonServicesDelegate;
        
        private EndOperationDelegate onEndGetSeasonServicesDelegate;
        
        private System.Threading.SendOrPostCallback onGetSeasonServicesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSeasonServiceHymnsDelegate;
        
        private EndOperationDelegate onEndGetSeasonServiceHymnsDelegate;
        
        private System.Threading.SendOrPostCallback onGetSeasonServiceHymnsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSeasonServiceHymnTextDelegate;
        
        private EndOperationDelegate onEndGetSeasonServiceHymnTextDelegate;
        
        private System.Threading.SendOrPostCallback onGetSeasonServiceHymnTextCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public HazzatWebServiceSoapClient() : 
                base(HazzatWebServiceSoapClient.GetDefaultBinding(), HazzatWebServiceSoapClient.GetDefaultEndpointAddress()) {
        }
        
        public HazzatWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(HazzatWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), HazzatWebServiceSoapClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public HazzatWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HazzatWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public HazzatWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HazzatWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public HazzatWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetSeasonsCompletedEventArgs> GetSeasonsCompleted;
        
        public event System.EventHandler<GetSeasonServicesCompletedEventArgs> GetSeasonServicesCompleted;
        
        public event System.EventHandler<GetSeasonServiceHymnsCompletedEventArgs> GetSeasonServiceHymnsCompleted;
        
        public event System.EventHandler<GetSeasonServiceHymnTextCompletedEventArgs> GetSeasonServiceHymnTextCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Hazzat.HazzatService.HazzatWebServiceSoap.BeginGetSeasons(Hazzat.HazzatService.GetSeasonsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSeasons(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetSeasons(bool isDateSpecific, System.AsyncCallback callback, object asyncState) {
            Hazzat.HazzatService.GetSeasonsRequest inValue = new Hazzat.HazzatService.GetSeasonsRequest();
            inValue.Body = new Hazzat.HazzatService.GetSeasonsRequestBody();
            inValue.Body.isDateSpecific = isDateSpecific;
            return ((Hazzat.HazzatService.HazzatWebServiceSoap)(this)).BeginGetSeasons(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hazzat.HazzatService.GetSeasonsResponse Hazzat.HazzatService.HazzatWebServiceSoap.EndGetSeasons(System.IAsyncResult result) {
            return base.Channel.EndGetSeasons(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.SeasonInfo> EndGetSeasons(System.IAsyncResult result) {
            Hazzat.HazzatService.GetSeasonsResponse retVal = ((Hazzat.HazzatService.HazzatWebServiceSoap)(this)).EndGetSeasons(result);
            return retVal.Body.GetSeasonsResult;
        }
        
        private System.IAsyncResult OnBeginGetSeasons(object[] inValues, System.AsyncCallback callback, object asyncState) {
            bool isDateSpecific = ((bool)(inValues[0]));
            return this.BeginGetSeasons(isDateSpecific, callback, asyncState);
        }
        
        private object[] OnEndGetSeasons(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.SeasonInfo> retVal = this.EndGetSeasons(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSeasonsCompleted(object state) {
            if ((this.GetSeasonsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSeasonsCompleted(this, new GetSeasonsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSeasonsAsync(bool isDateSpecific) {
            this.GetSeasonsAsync(isDateSpecific, null);
        }
        
        public void GetSeasonsAsync(bool isDateSpecific, object userState) {
            if ((this.onBeginGetSeasonsDelegate == null)) {
                this.onBeginGetSeasonsDelegate = new BeginOperationDelegate(this.OnBeginGetSeasons);
            }
            if ((this.onEndGetSeasonsDelegate == null)) {
                this.onEndGetSeasonsDelegate = new EndOperationDelegate(this.OnEndGetSeasons);
            }
            if ((this.onGetSeasonsCompletedDelegate == null)) {
                this.onGetSeasonsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSeasonsCompleted);
            }
            base.InvokeAsync(this.onBeginGetSeasonsDelegate, new object[] {
                        isDateSpecific}, this.onEndGetSeasonsDelegate, this.onGetSeasonsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Hazzat.HazzatService.HazzatWebServiceSoap.BeginGetSeasonServices(Hazzat.HazzatService.GetSeasonServicesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSeasonServices(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetSeasonServices(int seasonId, System.AsyncCallback callback, object asyncState) {
            Hazzat.HazzatService.GetSeasonServicesRequest inValue = new Hazzat.HazzatService.GetSeasonServicesRequest();
            inValue.Body = new Hazzat.HazzatService.GetSeasonServicesRequestBody();
            inValue.Body.seasonId = seasonId;
            return ((Hazzat.HazzatService.HazzatWebServiceSoap)(this)).BeginGetSeasonServices(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hazzat.HazzatService.GetSeasonServicesResponse Hazzat.HazzatService.HazzatWebServiceSoap.EndGetSeasonServices(System.IAsyncResult result) {
            return base.Channel.EndGetSeasonServices(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.StructureInfo> EndGetSeasonServices(System.IAsyncResult result) {
            Hazzat.HazzatService.GetSeasonServicesResponse retVal = ((Hazzat.HazzatService.HazzatWebServiceSoap)(this)).EndGetSeasonServices(result);
            return retVal.Body.GetSeasonServicesResult;
        }
        
        private System.IAsyncResult OnBeginGetSeasonServices(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int seasonId = ((int)(inValues[0]));
            return this.BeginGetSeasonServices(seasonId, callback, asyncState);
        }
        
        private object[] OnEndGetSeasonServices(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.StructureInfo> retVal = this.EndGetSeasonServices(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSeasonServicesCompleted(object state) {
            if ((this.GetSeasonServicesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSeasonServicesCompleted(this, new GetSeasonServicesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSeasonServicesAsync(int seasonId) {
            this.GetSeasonServicesAsync(seasonId, null);
        }
        
        public void GetSeasonServicesAsync(int seasonId, object userState) {
            if ((this.onBeginGetSeasonServicesDelegate == null)) {
                this.onBeginGetSeasonServicesDelegate = new BeginOperationDelegate(this.OnBeginGetSeasonServices);
            }
            if ((this.onEndGetSeasonServicesDelegate == null)) {
                this.onEndGetSeasonServicesDelegate = new EndOperationDelegate(this.OnEndGetSeasonServices);
            }
            if ((this.onGetSeasonServicesCompletedDelegate == null)) {
                this.onGetSeasonServicesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSeasonServicesCompleted);
            }
            base.InvokeAsync(this.onBeginGetSeasonServicesDelegate, new object[] {
                        seasonId}, this.onEndGetSeasonServicesDelegate, this.onGetSeasonServicesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Hazzat.HazzatService.HazzatWebServiceSoap.BeginGetSeasonServiceHymns(Hazzat.HazzatService.GetSeasonServiceHymnsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSeasonServiceHymns(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetSeasonServiceHymns(int structureId, System.AsyncCallback callback, object asyncState) {
            Hazzat.HazzatService.GetSeasonServiceHymnsRequest inValue = new Hazzat.HazzatService.GetSeasonServiceHymnsRequest();
            inValue.Body = new Hazzat.HazzatService.GetSeasonServiceHymnsRequestBody();
            inValue.Body.structureId = structureId;
            return ((Hazzat.HazzatService.HazzatWebServiceSoap)(this)).BeginGetSeasonServiceHymns(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hazzat.HazzatService.GetSeasonServiceHymnsResponse Hazzat.HazzatService.HazzatWebServiceSoap.EndGetSeasonServiceHymns(System.IAsyncResult result) {
            return base.Channel.EndGetSeasonServiceHymns(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.ServiceHymnInfo> EndGetSeasonServiceHymns(System.IAsyncResult result) {
            Hazzat.HazzatService.GetSeasonServiceHymnsResponse retVal = ((Hazzat.HazzatService.HazzatWebServiceSoap)(this)).EndGetSeasonServiceHymns(result);
            return retVal.Body.GetSeasonServiceHymnsResult;
        }
        
        private System.IAsyncResult OnBeginGetSeasonServiceHymns(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int structureId = ((int)(inValues[0]));
            return this.BeginGetSeasonServiceHymns(structureId, callback, asyncState);
        }
        
        private object[] OnEndGetSeasonServiceHymns(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.ServiceHymnInfo> retVal = this.EndGetSeasonServiceHymns(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSeasonServiceHymnsCompleted(object state) {
            if ((this.GetSeasonServiceHymnsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSeasonServiceHymnsCompleted(this, new GetSeasonServiceHymnsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSeasonServiceHymnsAsync(int structureId) {
            this.GetSeasonServiceHymnsAsync(structureId, null);
        }
        
        public void GetSeasonServiceHymnsAsync(int structureId, object userState) {
            if ((this.onBeginGetSeasonServiceHymnsDelegate == null)) {
                this.onBeginGetSeasonServiceHymnsDelegate = new BeginOperationDelegate(this.OnBeginGetSeasonServiceHymns);
            }
            if ((this.onEndGetSeasonServiceHymnsDelegate == null)) {
                this.onEndGetSeasonServiceHymnsDelegate = new EndOperationDelegate(this.OnEndGetSeasonServiceHymns);
            }
            if ((this.onGetSeasonServiceHymnsCompletedDelegate == null)) {
                this.onGetSeasonServiceHymnsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSeasonServiceHymnsCompleted);
            }
            base.InvokeAsync(this.onBeginGetSeasonServiceHymnsDelegate, new object[] {
                        structureId}, this.onEndGetSeasonServiceHymnsDelegate, this.onGetSeasonServiceHymnsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Hazzat.HazzatService.HazzatWebServiceSoap.BeginGetSeasonServiceHymnText(Hazzat.HazzatService.GetSeasonServiceHymnTextRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSeasonServiceHymnText(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetSeasonServiceHymnText(int ServiceHymnId, System.AsyncCallback callback, object asyncState) {
            Hazzat.HazzatService.GetSeasonServiceHymnTextRequest inValue = new Hazzat.HazzatService.GetSeasonServiceHymnTextRequest();
            inValue.Body = new Hazzat.HazzatService.GetSeasonServiceHymnTextRequestBody();
            inValue.Body.ServiceHymnId = ServiceHymnId;
            return ((Hazzat.HazzatService.HazzatWebServiceSoap)(this)).BeginGetSeasonServiceHymnText(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hazzat.HazzatService.GetSeasonServiceHymnTextResponse Hazzat.HazzatService.HazzatWebServiceSoap.EndGetSeasonServiceHymnText(System.IAsyncResult result) {
            return base.Channel.EndGetSeasonServiceHymnText(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.ServiceHymnsContentInfo> EndGetSeasonServiceHymnText(System.IAsyncResult result) {
            Hazzat.HazzatService.GetSeasonServiceHymnTextResponse retVal = ((Hazzat.HazzatService.HazzatWebServiceSoap)(this)).EndGetSeasonServiceHymnText(result);
            return retVal.Body.GetSeasonServiceHymnTextResult;
        }
        
        private System.IAsyncResult OnBeginGetSeasonServiceHymnText(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int ServiceHymnId = ((int)(inValues[0]));
            return this.BeginGetSeasonServiceHymnText(ServiceHymnId, callback, asyncState);
        }
        
        private object[] OnEndGetSeasonServiceHymnText(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Hazzat.HazzatService.ServiceHymnsContentInfo> retVal = this.EndGetSeasonServiceHymnText(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSeasonServiceHymnTextCompleted(object state) {
            if ((this.GetSeasonServiceHymnTextCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSeasonServiceHymnTextCompleted(this, new GetSeasonServiceHymnTextCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSeasonServiceHymnTextAsync(int ServiceHymnId) {
            this.GetSeasonServiceHymnTextAsync(ServiceHymnId, null);
        }
        
        public void GetSeasonServiceHymnTextAsync(int ServiceHymnId, object userState) {
            if ((this.onBeginGetSeasonServiceHymnTextDelegate == null)) {
                this.onBeginGetSeasonServiceHymnTextDelegate = new BeginOperationDelegate(this.OnBeginGetSeasonServiceHymnText);
            }
            if ((this.onEndGetSeasonServiceHymnTextDelegate == null)) {
                this.onEndGetSeasonServiceHymnTextDelegate = new EndOperationDelegate(this.OnEndGetSeasonServiceHymnText);
            }
            if ((this.onGetSeasonServiceHymnTextCompletedDelegate == null)) {
                this.onGetSeasonServiceHymnTextCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSeasonServiceHymnTextCompleted);
            }
            base.InvokeAsync(this.onBeginGetSeasonServiceHymnTextDelegate, new object[] {
                        ServiceHymnId}, this.onEndGetSeasonServiceHymnTextDelegate, this.onGetSeasonServiceHymnTextCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Hazzat.HazzatService.HazzatWebServiceSoap CreateChannel() {
            return new HazzatWebServiceSoapClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.HazzatWebServiceSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.HazzatWebServiceSoap)) {
                return new System.ServiceModel.EndpointAddress("http://hazzat.com/DesktopModules/Hymns/WebService/HazzatWebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return HazzatWebServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.HazzatWebServiceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return HazzatWebServiceSoapClient.GetEndpointAddress(EndpointConfiguration.HazzatWebServiceSoap);
        }
        
        private class HazzatWebServiceSoapClientChannel : ChannelBase<Hazzat.HazzatService.HazzatWebServiceSoap>, Hazzat.HazzatService.HazzatWebServiceSoap {
            
            public HazzatWebServiceSoapClientChannel(System.ServiceModel.ClientBase<Hazzat.HazzatService.HazzatWebServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetSeasons(Hazzat.HazzatService.GetSeasonsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetSeasons", _args, callback, asyncState);
                return _result;
            }
            
            public Hazzat.HazzatService.GetSeasonsResponse EndGetSeasons(System.IAsyncResult result) {
                object[] _args = new object[0];
                Hazzat.HazzatService.GetSeasonsResponse _result = ((Hazzat.HazzatService.GetSeasonsResponse)(base.EndInvoke("GetSeasons", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSeasonServices(Hazzat.HazzatService.GetSeasonServicesRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetSeasonServices", _args, callback, asyncState);
                return _result;
            }
            
            public Hazzat.HazzatService.GetSeasonServicesResponse EndGetSeasonServices(System.IAsyncResult result) {
                object[] _args = new object[0];
                Hazzat.HazzatService.GetSeasonServicesResponse _result = ((Hazzat.HazzatService.GetSeasonServicesResponse)(base.EndInvoke("GetSeasonServices", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSeasonServiceHymns(Hazzat.HazzatService.GetSeasonServiceHymnsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetSeasonServiceHymns", _args, callback, asyncState);
                return _result;
            }
            
            public Hazzat.HazzatService.GetSeasonServiceHymnsResponse EndGetSeasonServiceHymns(System.IAsyncResult result) {
                object[] _args = new object[0];
                Hazzat.HazzatService.GetSeasonServiceHymnsResponse _result = ((Hazzat.HazzatService.GetSeasonServiceHymnsResponse)(base.EndInvoke("GetSeasonServiceHymns", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSeasonServiceHymnText(Hazzat.HazzatService.GetSeasonServiceHymnTextRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetSeasonServiceHymnText", _args, callback, asyncState);
                return _result;
            }
            
            public Hazzat.HazzatService.GetSeasonServiceHymnTextResponse EndGetSeasonServiceHymnText(System.IAsyncResult result) {
                object[] _args = new object[0];
                Hazzat.HazzatService.GetSeasonServiceHymnTextResponse _result = ((Hazzat.HazzatService.GetSeasonServiceHymnTextResponse)(base.EndInvoke("GetSeasonServiceHymnText", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
            
            HazzatWebServiceSoap,
        }
    }
}
