//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://hazzat.com/", ClrNamespace="hazzat.com")]

// 
// This code was auto-generated by SlSvcUtil, version 3.7.0.0
// 
namespace hazzat.com
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeasonInfo", Namespace="http://hazzat.com/")]
    public partial class SeasonInfo : object
    {
        
        private int ItemIdField;
        
        private string NameField;
        
        private int ServiceHymnsCountField;
        
        private string VerseField;
        
        private int Season_OrderField;
        
        private int Reason_IDField;
        
        private string Reason_NameField;
        
        private bool Date_SpecificField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ItemId
        {
            get
            {
                return this.ItemIdField;
            }
            set
            {
                this.ItemIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ServiceHymnsCount
        {
            get
            {
                return this.ServiceHymnsCountField;
            }
            set
            {
                this.ServiceHymnsCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Verse
        {
            get
            {
                return this.VerseField;
            }
            set
            {
                this.VerseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Season_Order
        {
            get
            {
                return this.Season_OrderField;
            }
            set
            {
                this.Season_OrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Reason_ID
        {
            get
            {
                return this.Reason_IDField;
            }
            set
            {
                this.Reason_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Reason_Name
        {
            get
            {
                return this.Reason_NameField;
            }
            set
            {
                this.Reason_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool Date_Specific
        {
            get
            {
                return this.Date_SpecificField;
            }
            set
            {
                this.Date_SpecificField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructureInfo", Namespace="http://hazzat.com/")]
    public partial class StructureInfo : object
    {
        
        private int ItemIdField;
        
        private string NameField;
        
        private int Season_IDField;
        
        private string Season_NameField;
        
        private string Season_VerseField;
        
        private int Reason_IDField;
        
        private int Service_OrderField;
        
        private int Service_IDField;
        
        private string Service_NameField;
        
        private bool Has_TextField;
        
        private bool Has_HazzatField;
        
        private bool Has_VerticalHazzatField;
        
        private bool Has_MusicField;
        
        private bool Has_AudioField;
        
        private bool Has_VideoField;
        
        private bool Has_InformationField;
        
        private int Text_CountField;
        
        private int Hazzat_CountField;
        
        private int VerticalHazzat_CountField;
        
        private int Music_CountField;
        
        private int Audio_CountField;
        
        private int Video_CountField;
        
        private int Information_CountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ItemId
        {
            get
            {
                return this.ItemIdField;
            }
            set
            {
                this.ItemIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Season_ID
        {
            get
            {
                return this.Season_IDField;
            }
            set
            {
                this.Season_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Season_Name
        {
            get
            {
                return this.Season_NameField;
            }
            set
            {
                this.Season_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Season_Verse
        {
            get
            {
                return this.Season_VerseField;
            }
            set
            {
                this.Season_VerseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Reason_ID
        {
            get
            {
                return this.Reason_IDField;
            }
            set
            {
                this.Reason_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Service_Order
        {
            get
            {
                return this.Service_OrderField;
            }
            set
            {
                this.Service_OrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Service_ID
        {
            get
            {
                return this.Service_IDField;
            }
            set
            {
                this.Service_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Service_Name
        {
            get
            {
                return this.Service_NameField;
            }
            set
            {
                this.Service_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool Has_Text
        {
            get
            {
                return this.Has_TextField;
            }
            set
            {
                this.Has_TextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool Has_Hazzat
        {
            get
            {
                return this.Has_HazzatField;
            }
            set
            {
                this.Has_HazzatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public bool Has_VerticalHazzat
        {
            get
            {
                return this.Has_VerticalHazzatField;
            }
            set
            {
                this.Has_VerticalHazzatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool Has_Music
        {
            get
            {
                return this.Has_MusicField;
            }
            set
            {
                this.Has_MusicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool Has_Audio
        {
            get
            {
                return this.Has_AudioField;
            }
            set
            {
                this.Has_AudioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public bool Has_Video
        {
            get
            {
                return this.Has_VideoField;
            }
            set
            {
                this.Has_VideoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public bool Has_Information
        {
            get
            {
                return this.Has_InformationField;
            }
            set
            {
                this.Has_InformationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public int Text_Count
        {
            get
            {
                return this.Text_CountField;
            }
            set
            {
                this.Text_CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public int Hazzat_Count
        {
            get
            {
                return this.Hazzat_CountField;
            }
            set
            {
                this.Hazzat_CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public int VerticalHazzat_Count
        {
            get
            {
                return this.VerticalHazzat_CountField;
            }
            set
            {
                this.VerticalHazzat_CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public int Music_Count
        {
            get
            {
                return this.Music_CountField;
            }
            set
            {
                this.Music_CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public int Audio_Count
        {
            get
            {
                return this.Audio_CountField;
            }
            set
            {
                this.Audio_CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public int Video_Count
        {
            get
            {
                return this.Video_CountField;
            }
            set
            {
                this.Video_CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public int Information_Count
        {
            get
            {
                return this.Information_CountField;
            }
            set
            {
                this.Information_CountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceHymnInfo", Namespace="http://hazzat.com/")]
    public partial class ServiceHymnInfo : object
    {
        
        private int ItemIdField;
        
        private int Structure_IDField;
        
        private int Season_IDField;
        
        private string Season_NameField;
        
        private string Season_VerseField;
        
        private int Reason_IDField;
        
        private string Structure_NameField;
        
        private string Service_NameField;
        
        private int Hymn_OrderField;
        
        private string TitleField;
        
        private string ServiceHymn_LongTitleField;
        
        private bool Has_TextField;
        
        private bool Has_HazzatField;
        
        private bool Has_VerticalHazzatField;
        
        private bool Has_MusicField;
        
        private bool Has_AudioField;
        
        private bool Has_VideoField;
        
        private bool Has_InformationField;
        
        private int Text_CountField;
        
        private int Hazzat_CountField;
        
        private int VerticalHazzat_CountField;
        
        private int Music_CountField;
        
        private int Audio_CountField;
        
        private int Video_CountField;
        
        private int Information_CountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ItemId
        {
            get
            {
                return this.ItemIdField;
            }
            set
            {
                this.ItemIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Structure_ID
        {
            get
            {
                return this.Structure_IDField;
            }
            set
            {
                this.Structure_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Season_ID
        {
            get
            {
                return this.Season_IDField;
            }
            set
            {
                this.Season_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Season_Name
        {
            get
            {
                return this.Season_NameField;
            }
            set
            {
                this.Season_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Season_Verse
        {
            get
            {
                return this.Season_VerseField;
            }
            set
            {
                this.Season_VerseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Reason_ID
        {
            get
            {
                return this.Reason_IDField;
            }
            set
            {
                this.Reason_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Structure_Name
        {
            get
            {
                return this.Structure_NameField;
            }
            set
            {
                this.Structure_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Service_Name
        {
            get
            {
                return this.Service_NameField;
            }
            set
            {
                this.Service_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Hymn_Order
        {
            get
            {
                return this.Hymn_OrderField;
            }
            set
            {
                this.Hymn_OrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ServiceHymn_LongTitle
        {
            get
            {
                return this.ServiceHymn_LongTitleField;
            }
            set
            {
                this.ServiceHymn_LongTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public bool Has_Text
        {
            get
            {
                return this.Has_TextField;
            }
            set
            {
                this.Has_TextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool Has_Hazzat
        {
            get
            {
                return this.Has_HazzatField;
            }
            set
            {
                this.Has_HazzatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool Has_VerticalHazzat
        {
            get
            {
                return this.Has_VerticalHazzatField;
            }
            set
            {
                this.Has_VerticalHazzatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public bool Has_Music
        {
            get
            {
                return this.Has_MusicField;
            }
            set
            {
                this.Has_MusicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public bool Has_Audio
        {
            get
            {
                return this.Has_AudioField;
            }
            set
            {
                this.Has_AudioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public bool Has_Video
        {
            get
            {
                return this.Has_VideoField;
            }
            set
            {
                this.Has_VideoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public bool Has_Information
        {
            get
            {
                return this.Has_InformationField;
            }
            set
            {
                this.Has_InformationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public int Text_Count
        {
            get
            {
                return this.Text_CountField;
            }
            set
            {
                this.Text_CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public int Hazzat_Count
        {
            get
            {
                return this.Hazzat_CountField;
            }
            set
            {
                this.Hazzat_CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public int VerticalHazzat_Count
        {
            get
            {
                return this.VerticalHazzat_CountField;
            }
            set
            {
                this.VerticalHazzat_CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public int Music_Count
        {
            get
            {
                return this.Music_CountField;
            }
            set
            {
                this.Music_CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public int Audio_Count
        {
            get
            {
                return this.Audio_CountField;
            }
            set
            {
                this.Audio_CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public int Video_Count
        {
            get
            {
                return this.Video_CountField;
            }
            set
            {
                this.Video_CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public int Information_Count
        {
            get
            {
                return this.Information_CountField;
            }
            set
            {
                this.Information_CountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceHymnsContentInfo", Namespace="http://hazzat.com/")]
    public partial class ServiceHymnsContentInfo : object
    {
        
        private int ItemIdField;
        
        private string TitleField;
        
        private string Structure_NameField;
        
        private int ServiceHymn_IDField;
        
        private string ServiceHymn_NameField;
        
        private int Content_IDField;
        
        private int Format_IDField;
        
        private string Format_NameField;
        
        private int Type_IDField;
        
        private string Type_NameField;
        
        private int Tune_IDField;
        
        private string Tune_NameField;
        
        private string InfoField;
        
        private string Content_EnglishField;
        
        private string Content_CopticField;
        
        private string Content_ArabicField;
        
        private System.DateTime Updated_TimeStampField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ItemId
        {
            get
            {
                return this.ItemIdField;
            }
            set
            {
                this.ItemIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Structure_Name
        {
            get
            {
                return this.Structure_NameField;
            }
            set
            {
                this.Structure_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int ServiceHymn_ID
        {
            get
            {
                return this.ServiceHymn_IDField;
            }
            set
            {
                this.ServiceHymn_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ServiceHymn_Name
        {
            get
            {
                return this.ServiceHymn_NameField;
            }
            set
            {
                this.ServiceHymn_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Content_ID
        {
            get
            {
                return this.Content_IDField;
            }
            set
            {
                this.Content_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Format_ID
        {
            get
            {
                return this.Format_IDField;
            }
            set
            {
                this.Format_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Format_Name
        {
            get
            {
                return this.Format_NameField;
            }
            set
            {
                this.Format_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Type_ID
        {
            get
            {
                return this.Type_IDField;
            }
            set
            {
                this.Type_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Type_Name
        {
            get
            {
                return this.Type_NameField;
            }
            set
            {
                this.Type_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int Tune_ID
        {
            get
            {
                return this.Tune_IDField;
            }
            set
            {
                this.Tune_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Tune_Name
        {
            get
            {
                return this.Tune_NameField;
            }
            set
            {
                this.Tune_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Info
        {
            get
            {
                return this.InfoField;
            }
            set
            {
                this.InfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Content_English
        {
            get
            {
                return this.Content_EnglishField;
            }
            set
            {
                this.Content_EnglishField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Content_Coptic
        {
            get
            {
                return this.Content_CopticField;
            }
            set
            {
                this.Content_CopticField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Content_Arabic
        {
            get
            {
                return this.Content_ArabicField;
            }
            set
            {
                this.Content_ArabicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public System.DateTime Updated_TimeStamp
        {
            get
            {
                return this.Updated_TimeStampField;
            }
            set
            {
                this.Updated_TimeStampField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://hazzat.com/", ConfigurationName="HazzatWebServiceSoap")]
public interface HazzatWebServiceSoap
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hazzat.com/GetSeasons", ReplyAction="*")]
    System.IAsyncResult BeginGetSeasons(GetSeasonsRequest request, System.AsyncCallback callback, object asyncState);
    
    GetSeasonsResponse EndGetSeasons(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hazzat.com/GetSeasonServices", ReplyAction="*")]
    System.IAsyncResult BeginGetSeasonServices(GetSeasonServicesRequest request, System.AsyncCallback callback, object asyncState);
    
    GetSeasonServicesResponse EndGetSeasonServices(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hazzat.com/GetSeasonServiceHymns", ReplyAction="*")]
    System.IAsyncResult BeginGetSeasonServiceHymns(GetSeasonServiceHymnsRequest request, System.AsyncCallback callback, object asyncState);
    
    GetSeasonServiceHymnsResponse EndGetSeasonServiceHymns(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hazzat.com/GetTextRowDelimiterToken", ReplyAction="*")]
    System.IAsyncResult BeginGetTextRowDelimiterToken(GetTextRowDelimiterTokenRequest request, System.AsyncCallback callback, object asyncState);
    
    GetTextRowDelimiterTokenResponse EndGetTextRowDelimiterToken(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hazzat.com/GetSeasonServiceHymnText", ReplyAction="*")]
    System.IAsyncResult BeginGetSeasonServiceHymnText(GetSeasonServiceHymnTextRequest request, System.AsyncCallback callback, object asyncState);
    
    GetSeasonServiceHymnTextResponse EndGetSeasonServiceHymnText(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hazzat.com/GetSeasonServiceHymnHazzat", ReplyAction="*")]
    System.IAsyncResult BeginGetSeasonServiceHymnHazzat(GetSeasonServiceHymnHazzatRequest request, System.AsyncCallback callback, object asyncState);
    
    GetSeasonServiceHymnHazzatResponse EndGetSeasonServiceHymnHazzat(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hazzat.com/GetSeasonServiceHymnVerticalHazzat", ReplyAction="*")]
    System.IAsyncResult BeginGetSeasonServiceHymnVerticalHazzat(GetSeasonServiceHymnVerticalHazzatRequest request, System.AsyncCallback callback, object asyncState);
    
    GetSeasonServiceHymnVerticalHazzatResponse EndGetSeasonServiceHymnVerticalHazzat(System.IAsyncResult result);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetSeasonsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasons", Namespace="http://hazzat.com/", Order=0)]
    public GetSeasonsRequestBody Body;
    
    public GetSeasonsRequest()
    {
    }
    
    public GetSeasonsRequest(GetSeasonsRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
public partial class GetSeasonsRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public bool isDateSpecific;
    
    public GetSeasonsRequestBody()
    {
    }
    
    public GetSeasonsRequestBody(bool isDateSpecific)
    {
        this.isDateSpecific = isDateSpecific;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetSeasonsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasonsResponse", Namespace="http://hazzat.com/", Order=0)]
    public GetSeasonsResponseBody Body;
    
    public GetSeasonsResponse()
    {
    }
    
    public GetSeasonsResponse(GetSeasonsResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
public partial class GetSeasonsResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public hazzat.com.SeasonInfo[] GetSeasonsResult;
    
    public GetSeasonsResponseBody()
    {
    }
    
    public GetSeasonsResponseBody(hazzat.com.SeasonInfo[] GetSeasonsResult)
    {
        this.GetSeasonsResult = GetSeasonsResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetSeasonServicesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasonServices", Namespace="http://hazzat.com/", Order=0)]
    public GetSeasonServicesRequestBody Body;
    
    public GetSeasonServicesRequest()
    {
    }
    
    public GetSeasonServicesRequest(GetSeasonServicesRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
public partial class GetSeasonServicesRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public int seasonId;
    
    public GetSeasonServicesRequestBody()
    {
    }
    
    public GetSeasonServicesRequestBody(int seasonId)
    {
        this.seasonId = seasonId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetSeasonServicesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasonServicesResponse", Namespace="http://hazzat.com/", Order=0)]
    public GetSeasonServicesResponseBody Body;
    
    public GetSeasonServicesResponse()
    {
    }
    
    public GetSeasonServicesResponse(GetSeasonServicesResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
public partial class GetSeasonServicesResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public hazzat.com.StructureInfo[] GetSeasonServicesResult;
    
    public GetSeasonServicesResponseBody()
    {
    }
    
    public GetSeasonServicesResponseBody(hazzat.com.StructureInfo[] GetSeasonServicesResult)
    {
        this.GetSeasonServicesResult = GetSeasonServicesResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetSeasonServiceHymnsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasonServiceHymns", Namespace="http://hazzat.com/", Order=0)]
    public GetSeasonServiceHymnsRequestBody Body;
    
    public GetSeasonServiceHymnsRequest()
    {
    }
    
    public GetSeasonServiceHymnsRequest(GetSeasonServiceHymnsRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
public partial class GetSeasonServiceHymnsRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public int structureId;
    
    public GetSeasonServiceHymnsRequestBody()
    {
    }
    
    public GetSeasonServiceHymnsRequestBody(int structureId)
    {
        this.structureId = structureId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetSeasonServiceHymnsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasonServiceHymnsResponse", Namespace="http://hazzat.com/", Order=0)]
    public GetSeasonServiceHymnsResponseBody Body;
    
    public GetSeasonServiceHymnsResponse()
    {
    }
    
    public GetSeasonServiceHymnsResponse(GetSeasonServiceHymnsResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
public partial class GetSeasonServiceHymnsResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public hazzat.com.ServiceHymnInfo[] GetSeasonServiceHymnsResult;
    
    public GetSeasonServiceHymnsResponseBody()
    {
    }
    
    public GetSeasonServiceHymnsResponseBody(hazzat.com.ServiceHymnInfo[] GetSeasonServiceHymnsResult)
    {
        this.GetSeasonServiceHymnsResult = GetSeasonServiceHymnsResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetTextRowDelimiterTokenRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTextRowDelimiterToken", Namespace="http://hazzat.com/", Order=0)]
    public GetTextRowDelimiterTokenRequestBody Body;
    
    public GetTextRowDelimiterTokenRequest()
    {
    }
    
    public GetTextRowDelimiterTokenRequest(GetTextRowDelimiterTokenRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class GetTextRowDelimiterTokenRequestBody
{
    
    public GetTextRowDelimiterTokenRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetTextRowDelimiterTokenResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTextRowDelimiterTokenResponse", Namespace="http://hazzat.com/", Order=0)]
    public GetTextRowDelimiterTokenResponseBody Body;
    
    public GetTextRowDelimiterTokenResponse()
    {
    }
    
    public GetTextRowDelimiterTokenResponse(GetTextRowDelimiterTokenResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
public partial class GetTextRowDelimiterTokenResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetTextRowDelimiterTokenResult;
    
    public GetTextRowDelimiterTokenResponseBody()
    {
    }
    
    public GetTextRowDelimiterTokenResponseBody(string GetTextRowDelimiterTokenResult)
    {
        this.GetTextRowDelimiterTokenResult = GetTextRowDelimiterTokenResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetSeasonServiceHymnTextRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasonServiceHymnText", Namespace="http://hazzat.com/", Order=0)]
    public GetSeasonServiceHymnTextRequestBody Body;
    
    public GetSeasonServiceHymnTextRequest()
    {
    }
    
    public GetSeasonServiceHymnTextRequest(GetSeasonServiceHymnTextRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
public partial class GetSeasonServiceHymnTextRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public int ServiceHymnId;
    
    public GetSeasonServiceHymnTextRequestBody()
    {
    }
    
    public GetSeasonServiceHymnTextRequestBody(int ServiceHymnId)
    {
        this.ServiceHymnId = ServiceHymnId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetSeasonServiceHymnTextResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasonServiceHymnTextResponse", Namespace="http://hazzat.com/", Order=0)]
    public GetSeasonServiceHymnTextResponseBody Body;
    
    public GetSeasonServiceHymnTextResponse()
    {
    }
    
    public GetSeasonServiceHymnTextResponse(GetSeasonServiceHymnTextResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
public partial class GetSeasonServiceHymnTextResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public hazzat.com.ServiceHymnsContentInfo[] GetSeasonServiceHymnTextResult;
    
    public GetSeasonServiceHymnTextResponseBody()
    {
    }
    
    public GetSeasonServiceHymnTextResponseBody(hazzat.com.ServiceHymnsContentInfo[] GetSeasonServiceHymnTextResult)
    {
        this.GetSeasonServiceHymnTextResult = GetSeasonServiceHymnTextResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetSeasonServiceHymnHazzatRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasonServiceHymnHazzat", Namespace="http://hazzat.com/", Order=0)]
    public GetSeasonServiceHymnHazzatRequestBody Body;
    
    public GetSeasonServiceHymnHazzatRequest()
    {
    }
    
    public GetSeasonServiceHymnHazzatRequest(GetSeasonServiceHymnHazzatRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
public partial class GetSeasonServiceHymnHazzatRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public int ServiceHymnId;
    
    public GetSeasonServiceHymnHazzatRequestBody()
    {
    }
    
    public GetSeasonServiceHymnHazzatRequestBody(int ServiceHymnId)
    {
        this.ServiceHymnId = ServiceHymnId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetSeasonServiceHymnHazzatResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasonServiceHymnHazzatResponse", Namespace="http://hazzat.com/", Order=0)]
    public GetSeasonServiceHymnHazzatResponseBody Body;
    
    public GetSeasonServiceHymnHazzatResponse()
    {
    }
    
    public GetSeasonServiceHymnHazzatResponse(GetSeasonServiceHymnHazzatResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
public partial class GetSeasonServiceHymnHazzatResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public hazzat.com.ServiceHymnsContentInfo[] GetSeasonServiceHymnHazzatResult;
    
    public GetSeasonServiceHymnHazzatResponseBody()
    {
    }
    
    public GetSeasonServiceHymnHazzatResponseBody(hazzat.com.ServiceHymnsContentInfo[] GetSeasonServiceHymnHazzatResult)
    {
        this.GetSeasonServiceHymnHazzatResult = GetSeasonServiceHymnHazzatResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetSeasonServiceHymnVerticalHazzatRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasonServiceHymnVerticalHazzat", Namespace="http://hazzat.com/", Order=0)]
    public GetSeasonServiceHymnVerticalHazzatRequestBody Body;
    
    public GetSeasonServiceHymnVerticalHazzatRequest()
    {
    }
    
    public GetSeasonServiceHymnVerticalHazzatRequest(GetSeasonServiceHymnVerticalHazzatRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
public partial class GetSeasonServiceHymnVerticalHazzatRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public int ServiceHymnId;
    
    public GetSeasonServiceHymnVerticalHazzatRequestBody()
    {
    }
    
    public GetSeasonServiceHymnVerticalHazzatRequestBody(int ServiceHymnId)
    {
        this.ServiceHymnId = ServiceHymnId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetSeasonServiceHymnVerticalHazzatResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeasonServiceHymnVerticalHazzatResponse", Namespace="http://hazzat.com/", Order=0)]
    public GetSeasonServiceHymnVerticalHazzatResponseBody Body;
    
    public GetSeasonServiceHymnVerticalHazzatResponse()
    {
    }
    
    public GetSeasonServiceHymnVerticalHazzatResponse(GetSeasonServiceHymnVerticalHazzatResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://hazzat.com/")]
public partial class GetSeasonServiceHymnVerticalHazzatResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public hazzat.com.ServiceHymnsContentInfo[] GetSeasonServiceHymnVerticalHazzatResult;
    
    public GetSeasonServiceHymnVerticalHazzatResponseBody()
    {
    }
    
    public GetSeasonServiceHymnVerticalHazzatResponseBody(hazzat.com.ServiceHymnsContentInfo[] GetSeasonServiceHymnVerticalHazzatResult)
    {
        this.GetSeasonServiceHymnVerticalHazzatResult = GetSeasonServiceHymnVerticalHazzatResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface HazzatWebServiceSoapChannel : HazzatWebServiceSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetSeasonsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetSeasonsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public hazzat.com.SeasonInfo[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((hazzat.com.SeasonInfo[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetSeasonServicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetSeasonServicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public hazzat.com.StructureInfo[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((hazzat.com.StructureInfo[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetSeasonServiceHymnsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetSeasonServiceHymnsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public hazzat.com.ServiceHymnInfo[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((hazzat.com.ServiceHymnInfo[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetTextRowDelimiterTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetTextRowDelimiterTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetSeasonServiceHymnTextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetSeasonServiceHymnTextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public hazzat.com.ServiceHymnsContentInfo[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((hazzat.com.ServiceHymnsContentInfo[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetSeasonServiceHymnHazzatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetSeasonServiceHymnHazzatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public hazzat.com.ServiceHymnsContentInfo[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((hazzat.com.ServiceHymnsContentInfo[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetSeasonServiceHymnVerticalHazzatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetSeasonServiceHymnVerticalHazzatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public hazzat.com.ServiceHymnsContentInfo[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((hazzat.com.ServiceHymnsContentInfo[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HazzatWebServiceSoapClient : System.ServiceModel.ClientBase<HazzatWebServiceSoap>, HazzatWebServiceSoap
{
    
    private BeginOperationDelegate onBeginGetSeasonsDelegate;
    
    private EndOperationDelegate onEndGetSeasonsDelegate;
    
    private System.Threading.SendOrPostCallback onGetSeasonsCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetSeasonServicesDelegate;
    
    private EndOperationDelegate onEndGetSeasonServicesDelegate;
    
    private System.Threading.SendOrPostCallback onGetSeasonServicesCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetSeasonServiceHymnsDelegate;
    
    private EndOperationDelegate onEndGetSeasonServiceHymnsDelegate;
    
    private System.Threading.SendOrPostCallback onGetSeasonServiceHymnsCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetTextRowDelimiterTokenDelegate;
    
    private EndOperationDelegate onEndGetTextRowDelimiterTokenDelegate;
    
    private System.Threading.SendOrPostCallback onGetTextRowDelimiterTokenCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetSeasonServiceHymnTextDelegate;
    
    private EndOperationDelegate onEndGetSeasonServiceHymnTextDelegate;
    
    private System.Threading.SendOrPostCallback onGetSeasonServiceHymnTextCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetSeasonServiceHymnHazzatDelegate;
    
    private EndOperationDelegate onEndGetSeasonServiceHymnHazzatDelegate;
    
    private System.Threading.SendOrPostCallback onGetSeasonServiceHymnHazzatCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetSeasonServiceHymnVerticalHazzatDelegate;
    
    private EndOperationDelegate onEndGetSeasonServiceHymnVerticalHazzatDelegate;
    
    private System.Threading.SendOrPostCallback onGetSeasonServiceHymnVerticalHazzatCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public HazzatWebServiceSoapClient()
    {
    }
    
    public HazzatWebServiceSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HazzatWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HazzatWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HazzatWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<GetSeasonsCompletedEventArgs> GetSeasonsCompleted;
    
    public event System.EventHandler<GetSeasonServicesCompletedEventArgs> GetSeasonServicesCompleted;
    
    public event System.EventHandler<GetSeasonServiceHymnsCompletedEventArgs> GetSeasonServiceHymnsCompleted;
    
    public event System.EventHandler<GetTextRowDelimiterTokenCompletedEventArgs> GetTextRowDelimiterTokenCompleted;
    
    public event System.EventHandler<GetSeasonServiceHymnTextCompletedEventArgs> GetSeasonServiceHymnTextCompleted;
    
    public event System.EventHandler<GetSeasonServiceHymnHazzatCompletedEventArgs> GetSeasonServiceHymnHazzatCompleted;
    
    public event System.EventHandler<GetSeasonServiceHymnVerticalHazzatCompletedEventArgs> GetSeasonServiceHymnVerticalHazzatCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult HazzatWebServiceSoap.BeginGetSeasons(GetSeasonsRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetSeasons(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetSeasons(bool isDateSpecific, System.AsyncCallback callback, object asyncState)
    {
        GetSeasonsRequest inValue = new GetSeasonsRequest();
        inValue.Body = new GetSeasonsRequestBody();
        inValue.Body.isDateSpecific = isDateSpecific;
        return ((HazzatWebServiceSoap)(this)).BeginGetSeasons(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetSeasonsResponse HazzatWebServiceSoap.EndGetSeasons(System.IAsyncResult result)
    {
        return base.Channel.EndGetSeasons(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private hazzat.com.SeasonInfo[] EndGetSeasons(System.IAsyncResult result)
    {
        GetSeasonsResponse retVal = ((HazzatWebServiceSoap)(this)).EndGetSeasons(result);
        return retVal.Body.GetSeasonsResult;
    }
    
    private System.IAsyncResult OnBeginGetSeasons(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        bool isDateSpecific = ((bool)(inValues[0]));
        return this.BeginGetSeasons(isDateSpecific, callback, asyncState);
    }
    
    private object[] OnEndGetSeasons(System.IAsyncResult result)
    {
        hazzat.com.SeasonInfo[] retVal = this.EndGetSeasons(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetSeasonsCompleted(object state)
    {
        if ((this.GetSeasonsCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetSeasonsCompleted(this, new GetSeasonsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetSeasonsAsync(bool isDateSpecific)
    {
        this.GetSeasonsAsync(isDateSpecific, null);
    }
    
    public void GetSeasonsAsync(bool isDateSpecific, object userState)
    {
        if ((this.onBeginGetSeasonsDelegate == null))
        {
            this.onBeginGetSeasonsDelegate = new BeginOperationDelegate(this.OnBeginGetSeasons);
        }
        if ((this.onEndGetSeasonsDelegate == null))
        {
            this.onEndGetSeasonsDelegate = new EndOperationDelegate(this.OnEndGetSeasons);
        }
        if ((this.onGetSeasonsCompletedDelegate == null))
        {
            this.onGetSeasonsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSeasonsCompleted);
        }
        base.InvokeAsync(this.onBeginGetSeasonsDelegate, new object[] {
                    isDateSpecific}, this.onEndGetSeasonsDelegate, this.onGetSeasonsCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult HazzatWebServiceSoap.BeginGetSeasonServices(GetSeasonServicesRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetSeasonServices(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetSeasonServices(int seasonId, System.AsyncCallback callback, object asyncState)
    {
        GetSeasonServicesRequest inValue = new GetSeasonServicesRequest();
        inValue.Body = new GetSeasonServicesRequestBody();
        inValue.Body.seasonId = seasonId;
        return ((HazzatWebServiceSoap)(this)).BeginGetSeasonServices(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetSeasonServicesResponse HazzatWebServiceSoap.EndGetSeasonServices(System.IAsyncResult result)
    {
        return base.Channel.EndGetSeasonServices(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private hazzat.com.StructureInfo[] EndGetSeasonServices(System.IAsyncResult result)
    {
        GetSeasonServicesResponse retVal = ((HazzatWebServiceSoap)(this)).EndGetSeasonServices(result);
        return retVal.Body.GetSeasonServicesResult;
    }
    
    private System.IAsyncResult OnBeginGetSeasonServices(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        int seasonId = ((int)(inValues[0]));
        return this.BeginGetSeasonServices(seasonId, callback, asyncState);
    }
    
    private object[] OnEndGetSeasonServices(System.IAsyncResult result)
    {
        hazzat.com.StructureInfo[] retVal = this.EndGetSeasonServices(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetSeasonServicesCompleted(object state)
    {
        if ((this.GetSeasonServicesCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetSeasonServicesCompleted(this, new GetSeasonServicesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetSeasonServicesAsync(int seasonId)
    {
        this.GetSeasonServicesAsync(seasonId, null);
    }
    
    public void GetSeasonServicesAsync(int seasonId, object userState)
    {
        if ((this.onBeginGetSeasonServicesDelegate == null))
        {
            this.onBeginGetSeasonServicesDelegate = new BeginOperationDelegate(this.OnBeginGetSeasonServices);
        }
        if ((this.onEndGetSeasonServicesDelegate == null))
        {
            this.onEndGetSeasonServicesDelegate = new EndOperationDelegate(this.OnEndGetSeasonServices);
        }
        if ((this.onGetSeasonServicesCompletedDelegate == null))
        {
            this.onGetSeasonServicesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSeasonServicesCompleted);
        }
        base.InvokeAsync(this.onBeginGetSeasonServicesDelegate, new object[] {
                    seasonId}, this.onEndGetSeasonServicesDelegate, this.onGetSeasonServicesCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult HazzatWebServiceSoap.BeginGetSeasonServiceHymns(GetSeasonServiceHymnsRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetSeasonServiceHymns(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetSeasonServiceHymns(int structureId, System.AsyncCallback callback, object asyncState)
    {
        GetSeasonServiceHymnsRequest inValue = new GetSeasonServiceHymnsRequest();
        inValue.Body = new GetSeasonServiceHymnsRequestBody();
        inValue.Body.structureId = structureId;
        return ((HazzatWebServiceSoap)(this)).BeginGetSeasonServiceHymns(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetSeasonServiceHymnsResponse HazzatWebServiceSoap.EndGetSeasonServiceHymns(System.IAsyncResult result)
    {
        return base.Channel.EndGetSeasonServiceHymns(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private hazzat.com.ServiceHymnInfo[] EndGetSeasonServiceHymns(System.IAsyncResult result)
    {
        GetSeasonServiceHymnsResponse retVal = ((HazzatWebServiceSoap)(this)).EndGetSeasonServiceHymns(result);
        return retVal.Body.GetSeasonServiceHymnsResult;
    }
    
    private System.IAsyncResult OnBeginGetSeasonServiceHymns(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        int structureId = ((int)(inValues[0]));
        return this.BeginGetSeasonServiceHymns(structureId, callback, asyncState);
    }
    
    private object[] OnEndGetSeasonServiceHymns(System.IAsyncResult result)
    {
        hazzat.com.ServiceHymnInfo[] retVal = this.EndGetSeasonServiceHymns(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetSeasonServiceHymnsCompleted(object state)
    {
        if ((this.GetSeasonServiceHymnsCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetSeasonServiceHymnsCompleted(this, new GetSeasonServiceHymnsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetSeasonServiceHymnsAsync(int structureId)
    {
        this.GetSeasonServiceHymnsAsync(structureId, null);
    }
    
    public void GetSeasonServiceHymnsAsync(int structureId, object userState)
    {
        if ((this.onBeginGetSeasonServiceHymnsDelegate == null))
        {
            this.onBeginGetSeasonServiceHymnsDelegate = new BeginOperationDelegate(this.OnBeginGetSeasonServiceHymns);
        }
        if ((this.onEndGetSeasonServiceHymnsDelegate == null))
        {
            this.onEndGetSeasonServiceHymnsDelegate = new EndOperationDelegate(this.OnEndGetSeasonServiceHymns);
        }
        if ((this.onGetSeasonServiceHymnsCompletedDelegate == null))
        {
            this.onGetSeasonServiceHymnsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSeasonServiceHymnsCompleted);
        }
        base.InvokeAsync(this.onBeginGetSeasonServiceHymnsDelegate, new object[] {
                    structureId}, this.onEndGetSeasonServiceHymnsDelegate, this.onGetSeasonServiceHymnsCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult HazzatWebServiceSoap.BeginGetTextRowDelimiterToken(GetTextRowDelimiterTokenRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetTextRowDelimiterToken(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetTextRowDelimiterToken(System.AsyncCallback callback, object asyncState)
    {
        GetTextRowDelimiterTokenRequest inValue = new GetTextRowDelimiterTokenRequest();
        inValue.Body = new GetTextRowDelimiterTokenRequestBody();
        return ((HazzatWebServiceSoap)(this)).BeginGetTextRowDelimiterToken(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetTextRowDelimiterTokenResponse HazzatWebServiceSoap.EndGetTextRowDelimiterToken(System.IAsyncResult result)
    {
        return base.Channel.EndGetTextRowDelimiterToken(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private string EndGetTextRowDelimiterToken(System.IAsyncResult result)
    {
        GetTextRowDelimiterTokenResponse retVal = ((HazzatWebServiceSoap)(this)).EndGetTextRowDelimiterToken(result);
        return retVal.Body.GetTextRowDelimiterTokenResult;
    }
    
    private System.IAsyncResult OnBeginGetTextRowDelimiterToken(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginGetTextRowDelimiterToken(callback, asyncState);
    }
    
    private object[] OnEndGetTextRowDelimiterToken(System.IAsyncResult result)
    {
        string retVal = this.EndGetTextRowDelimiterToken(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetTextRowDelimiterTokenCompleted(object state)
    {
        if ((this.GetTextRowDelimiterTokenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetTextRowDelimiterTokenCompleted(this, new GetTextRowDelimiterTokenCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetTextRowDelimiterTokenAsync()
    {
        this.GetTextRowDelimiterTokenAsync(null);
    }
    
    public void GetTextRowDelimiterTokenAsync(object userState)
    {
        if ((this.onBeginGetTextRowDelimiterTokenDelegate == null))
        {
            this.onBeginGetTextRowDelimiterTokenDelegate = new BeginOperationDelegate(this.OnBeginGetTextRowDelimiterToken);
        }
        if ((this.onEndGetTextRowDelimiterTokenDelegate == null))
        {
            this.onEndGetTextRowDelimiterTokenDelegate = new EndOperationDelegate(this.OnEndGetTextRowDelimiterToken);
        }
        if ((this.onGetTextRowDelimiterTokenCompletedDelegate == null))
        {
            this.onGetTextRowDelimiterTokenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTextRowDelimiterTokenCompleted);
        }
        base.InvokeAsync(this.onBeginGetTextRowDelimiterTokenDelegate, null, this.onEndGetTextRowDelimiterTokenDelegate, this.onGetTextRowDelimiterTokenCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult HazzatWebServiceSoap.BeginGetSeasonServiceHymnText(GetSeasonServiceHymnTextRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetSeasonServiceHymnText(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetSeasonServiceHymnText(int ServiceHymnId, System.AsyncCallback callback, object asyncState)
    {
        GetSeasonServiceHymnTextRequest inValue = new GetSeasonServiceHymnTextRequest();
        inValue.Body = new GetSeasonServiceHymnTextRequestBody();
        inValue.Body.ServiceHymnId = ServiceHymnId;
        return ((HazzatWebServiceSoap)(this)).BeginGetSeasonServiceHymnText(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetSeasonServiceHymnTextResponse HazzatWebServiceSoap.EndGetSeasonServiceHymnText(System.IAsyncResult result)
    {
        return base.Channel.EndGetSeasonServiceHymnText(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private hazzat.com.ServiceHymnsContentInfo[] EndGetSeasonServiceHymnText(System.IAsyncResult result)
    {
        GetSeasonServiceHymnTextResponse retVal = ((HazzatWebServiceSoap)(this)).EndGetSeasonServiceHymnText(result);
        return retVal.Body.GetSeasonServiceHymnTextResult;
    }
    
    private System.IAsyncResult OnBeginGetSeasonServiceHymnText(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        int ServiceHymnId = ((int)(inValues[0]));
        return this.BeginGetSeasonServiceHymnText(ServiceHymnId, callback, asyncState);
    }
    
    private object[] OnEndGetSeasonServiceHymnText(System.IAsyncResult result)
    {
        hazzat.com.ServiceHymnsContentInfo[] retVal = this.EndGetSeasonServiceHymnText(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetSeasonServiceHymnTextCompleted(object state)
    {
        if ((this.GetSeasonServiceHymnTextCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetSeasonServiceHymnTextCompleted(this, new GetSeasonServiceHymnTextCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetSeasonServiceHymnTextAsync(int ServiceHymnId)
    {
        this.GetSeasonServiceHymnTextAsync(ServiceHymnId, null);
    }
    
    public void GetSeasonServiceHymnTextAsync(int ServiceHymnId, object userState)
    {
        if ((this.onBeginGetSeasonServiceHymnTextDelegate == null))
        {
            this.onBeginGetSeasonServiceHymnTextDelegate = new BeginOperationDelegate(this.OnBeginGetSeasonServiceHymnText);
        }
        if ((this.onEndGetSeasonServiceHymnTextDelegate == null))
        {
            this.onEndGetSeasonServiceHymnTextDelegate = new EndOperationDelegate(this.OnEndGetSeasonServiceHymnText);
        }
        if ((this.onGetSeasonServiceHymnTextCompletedDelegate == null))
        {
            this.onGetSeasonServiceHymnTextCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSeasonServiceHymnTextCompleted);
        }
        base.InvokeAsync(this.onBeginGetSeasonServiceHymnTextDelegate, new object[] {
                    ServiceHymnId}, this.onEndGetSeasonServiceHymnTextDelegate, this.onGetSeasonServiceHymnTextCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult HazzatWebServiceSoap.BeginGetSeasonServiceHymnHazzat(GetSeasonServiceHymnHazzatRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetSeasonServiceHymnHazzat(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetSeasonServiceHymnHazzat(int ServiceHymnId, System.AsyncCallback callback, object asyncState)
    {
        GetSeasonServiceHymnHazzatRequest inValue = new GetSeasonServiceHymnHazzatRequest();
        inValue.Body = new GetSeasonServiceHymnHazzatRequestBody();
        inValue.Body.ServiceHymnId = ServiceHymnId;
        return ((HazzatWebServiceSoap)(this)).BeginGetSeasonServiceHymnHazzat(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetSeasonServiceHymnHazzatResponse HazzatWebServiceSoap.EndGetSeasonServiceHymnHazzat(System.IAsyncResult result)
    {
        return base.Channel.EndGetSeasonServiceHymnHazzat(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private hazzat.com.ServiceHymnsContentInfo[] EndGetSeasonServiceHymnHazzat(System.IAsyncResult result)
    {
        GetSeasonServiceHymnHazzatResponse retVal = ((HazzatWebServiceSoap)(this)).EndGetSeasonServiceHymnHazzat(result);
        return retVal.Body.GetSeasonServiceHymnHazzatResult;
    }
    
    private System.IAsyncResult OnBeginGetSeasonServiceHymnHazzat(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        int ServiceHymnId = ((int)(inValues[0]));
        return this.BeginGetSeasonServiceHymnHazzat(ServiceHymnId, callback, asyncState);
    }
    
    private object[] OnEndGetSeasonServiceHymnHazzat(System.IAsyncResult result)
    {
        hazzat.com.ServiceHymnsContentInfo[] retVal = this.EndGetSeasonServiceHymnHazzat(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetSeasonServiceHymnHazzatCompleted(object state)
    {
        if ((this.GetSeasonServiceHymnHazzatCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetSeasonServiceHymnHazzatCompleted(this, new GetSeasonServiceHymnHazzatCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetSeasonServiceHymnHazzatAsync(int ServiceHymnId)
    {
        this.GetSeasonServiceHymnHazzatAsync(ServiceHymnId, null);
    }
    
    public void GetSeasonServiceHymnHazzatAsync(int ServiceHymnId, object userState)
    {
        if ((this.onBeginGetSeasonServiceHymnHazzatDelegate == null))
        {
            this.onBeginGetSeasonServiceHymnHazzatDelegate = new BeginOperationDelegate(this.OnBeginGetSeasonServiceHymnHazzat);
        }
        if ((this.onEndGetSeasonServiceHymnHazzatDelegate == null))
        {
            this.onEndGetSeasonServiceHymnHazzatDelegate = new EndOperationDelegate(this.OnEndGetSeasonServiceHymnHazzat);
        }
        if ((this.onGetSeasonServiceHymnHazzatCompletedDelegate == null))
        {
            this.onGetSeasonServiceHymnHazzatCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSeasonServiceHymnHazzatCompleted);
        }
        base.InvokeAsync(this.onBeginGetSeasonServiceHymnHazzatDelegate, new object[] {
                    ServiceHymnId}, this.onEndGetSeasonServiceHymnHazzatDelegate, this.onGetSeasonServiceHymnHazzatCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult HazzatWebServiceSoap.BeginGetSeasonServiceHymnVerticalHazzat(GetSeasonServiceHymnVerticalHazzatRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetSeasonServiceHymnVerticalHazzat(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetSeasonServiceHymnVerticalHazzat(int ServiceHymnId, System.AsyncCallback callback, object asyncState)
    {
        GetSeasonServiceHymnVerticalHazzatRequest inValue = new GetSeasonServiceHymnVerticalHazzatRequest();
        inValue.Body = new GetSeasonServiceHymnVerticalHazzatRequestBody();
        inValue.Body.ServiceHymnId = ServiceHymnId;
        return ((HazzatWebServiceSoap)(this)).BeginGetSeasonServiceHymnVerticalHazzat(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetSeasonServiceHymnVerticalHazzatResponse HazzatWebServiceSoap.EndGetSeasonServiceHymnVerticalHazzat(System.IAsyncResult result)
    {
        return base.Channel.EndGetSeasonServiceHymnVerticalHazzat(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private hazzat.com.ServiceHymnsContentInfo[] EndGetSeasonServiceHymnVerticalHazzat(System.IAsyncResult result)
    {
        GetSeasonServiceHymnVerticalHazzatResponse retVal = ((HazzatWebServiceSoap)(this)).EndGetSeasonServiceHymnVerticalHazzat(result);
        return retVal.Body.GetSeasonServiceHymnVerticalHazzatResult;
    }
    
    private System.IAsyncResult OnBeginGetSeasonServiceHymnVerticalHazzat(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        int ServiceHymnId = ((int)(inValues[0]));
        return this.BeginGetSeasonServiceHymnVerticalHazzat(ServiceHymnId, callback, asyncState);
    }
    
    private object[] OnEndGetSeasonServiceHymnVerticalHazzat(System.IAsyncResult result)
    {
        hazzat.com.ServiceHymnsContentInfo[] retVal = this.EndGetSeasonServiceHymnVerticalHazzat(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetSeasonServiceHymnVerticalHazzatCompleted(object state)
    {
        if ((this.GetSeasonServiceHymnVerticalHazzatCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetSeasonServiceHymnVerticalHazzatCompleted(this, new GetSeasonServiceHymnVerticalHazzatCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetSeasonServiceHymnVerticalHazzatAsync(int ServiceHymnId)
    {
        this.GetSeasonServiceHymnVerticalHazzatAsync(ServiceHymnId, null);
    }
    
    public void GetSeasonServiceHymnVerticalHazzatAsync(int ServiceHymnId, object userState)
    {
        if ((this.onBeginGetSeasonServiceHymnVerticalHazzatDelegate == null))
        {
            this.onBeginGetSeasonServiceHymnVerticalHazzatDelegate = new BeginOperationDelegate(this.OnBeginGetSeasonServiceHymnVerticalHazzat);
        }
        if ((this.onEndGetSeasonServiceHymnVerticalHazzatDelegate == null))
        {
            this.onEndGetSeasonServiceHymnVerticalHazzatDelegate = new EndOperationDelegate(this.OnEndGetSeasonServiceHymnVerticalHazzat);
        }
        if ((this.onGetSeasonServiceHymnVerticalHazzatCompletedDelegate == null))
        {
            this.onGetSeasonServiceHymnVerticalHazzatCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSeasonServiceHymnVerticalHazzatCompleted);
        }
        base.InvokeAsync(this.onBeginGetSeasonServiceHymnVerticalHazzatDelegate, new object[] {
                    ServiceHymnId}, this.onEndGetSeasonServiceHymnVerticalHazzatDelegate, this.onGetSeasonServiceHymnVerticalHazzatCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override HazzatWebServiceSoap CreateChannel()
    {
        return new HazzatWebServiceSoapClientChannel(this);
    }
    
    private class HazzatWebServiceSoapClientChannel : ChannelBase<HazzatWebServiceSoap>, HazzatWebServiceSoap
    {
        
        public HazzatWebServiceSoapClientChannel(System.ServiceModel.ClientBase<HazzatWebServiceSoap> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginGetSeasons(GetSeasonsRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetSeasons", _args, callback, asyncState);
            return _result;
        }
        
        public GetSeasonsResponse EndGetSeasons(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetSeasonsResponse _result = ((GetSeasonsResponse)(base.EndInvoke("GetSeasons", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetSeasonServices(GetSeasonServicesRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetSeasonServices", _args, callback, asyncState);
            return _result;
        }
        
        public GetSeasonServicesResponse EndGetSeasonServices(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetSeasonServicesResponse _result = ((GetSeasonServicesResponse)(base.EndInvoke("GetSeasonServices", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetSeasonServiceHymns(GetSeasonServiceHymnsRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetSeasonServiceHymns", _args, callback, asyncState);
            return _result;
        }
        
        public GetSeasonServiceHymnsResponse EndGetSeasonServiceHymns(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetSeasonServiceHymnsResponse _result = ((GetSeasonServiceHymnsResponse)(base.EndInvoke("GetSeasonServiceHymns", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetTextRowDelimiterToken(GetTextRowDelimiterTokenRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetTextRowDelimiterToken", _args, callback, asyncState);
            return _result;
        }
        
        public GetTextRowDelimiterTokenResponse EndGetTextRowDelimiterToken(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetTextRowDelimiterTokenResponse _result = ((GetTextRowDelimiterTokenResponse)(base.EndInvoke("GetTextRowDelimiterToken", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetSeasonServiceHymnText(GetSeasonServiceHymnTextRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetSeasonServiceHymnText", _args, callback, asyncState);
            return _result;
        }
        
        public GetSeasonServiceHymnTextResponse EndGetSeasonServiceHymnText(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetSeasonServiceHymnTextResponse _result = ((GetSeasonServiceHymnTextResponse)(base.EndInvoke("GetSeasonServiceHymnText", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetSeasonServiceHymnHazzat(GetSeasonServiceHymnHazzatRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetSeasonServiceHymnHazzat", _args, callback, asyncState);
            return _result;
        }
        
        public GetSeasonServiceHymnHazzatResponse EndGetSeasonServiceHymnHazzat(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetSeasonServiceHymnHazzatResponse _result = ((GetSeasonServiceHymnHazzatResponse)(base.EndInvoke("GetSeasonServiceHymnHazzat", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetSeasonServiceHymnVerticalHazzat(GetSeasonServiceHymnVerticalHazzatRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetSeasonServiceHymnVerticalHazzat", _args, callback, asyncState);
            return _result;
        }
        
        public GetSeasonServiceHymnVerticalHazzatResponse EndGetSeasonServiceHymnVerticalHazzat(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetSeasonServiceHymnVerticalHazzatResponse _result = ((GetSeasonServiceHymnVerticalHazzatResponse)(base.EndInvoke("GetSeasonServiceHymnVerticalHazzat", _args, result)));
            return _result;
        }
    }
}
